version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/app/
    ports:
      - "${PORT}:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - thermodynamic_web_db:/var/lib/mysql
volumes:
  thermodynamic_web_db: